# Generated by Django 4.1 on 2022-09-07 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_appuser_email_remove_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file',
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='app/contents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.content')),
            ],
        ),
    ]
