# Generated by Django 4.1 on 2022-09-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_content_file_contentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.appuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='app.content'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='app.appuser'),
        ),
    ]
