# Generated by Django 4.1 on 2022-09-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_subscriber_subscribe_subscriber_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
