# Generated by Django 4.1 on 2022-09-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
    ]
