# Generated by Django 4.1 on 2022-09-10 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_comment_content_comment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(default=1, upload_to='app/contents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
            preserve_default=False,
        ),
    ]
